Feature/pthread
tofixx/epic-battle-db pull request #24
Opened 2017-07-03 10:19 UTC by maxklenk

2017-07-03 15:44 UTC, maxklenk commented
Läuft gut, hat aber bei mir lokal keinen größeren Durchsatz.

Man könnte noch verbesserungen einbauen:
- Daten aus Threads zusammenrechen und in file schreiben
- Datenbanken gemeinsam benutzen
- Start der Tests gleichzeitig

..man kann es auch einfach mergen.

2017-07-03 16:00 UTC, tofixx requested changes
run more threads same time :)

2017-07-03 16:00 UTC, tofixx commented on runBenchmarks.sh
> +./benchmark_thread
missed empty line

2017-07-04 07:27 UTC, maxklenk commented on runBenchmarks.sh
> +./benchmark_thread
fixed

2017-07-10 10:55 UTC, merged